### PR TITLE
Places `renders` object in Item properties

### LINKED ISSUE #4: Placement in Items
The specification says "renders" should be in Item Properties, but the examples and schema seem to have it on the top-level. I think it should in the Item Properties. All extensions extend the Item Properties, which is the best-practice.

### PR DESCRIPTION
**Pull request by giorgiobasile**
Changes the JSON Schema, updates examples and docs.

Closes #4

### CODE REVIEW

**Comment by emmanuelmathot** [comment]
seems good to me.

**Review by emmanuelmathot — CHANGES_REQUESTED** [review]
Please just add your changes in the CHANGELOG

**Comment by giorgiobasile** [comment]
Thanks @emmanuelmathot! Should I update already the version number to 2.0.0 or that will be done at release time by you or other maintainers?

**Comment by emmanuelmathot** [comment]
We will prepare a PR for the v2 release.

**Comment by bmcandr** [comment]
Hey, @emmanuelmathot! I'm working on implementing the Render extension in `pystac` ([PR](https://github.com/stac-utils/pystac/pull/1465)) and noticed that this change moving the `renders` field into Item properties hasn't been released yet. When do you think this might get released? This change better aligns the extension spec with [the Item spec conventions for extensions](https://github.com/radiantearth/stac-spec/blob/master/extensions/README.md#:~:text=Additional%20attributes%20relating%20to%20an%20Item%20should%20be%20added%20into%20the%20Item%20Properties%20object%2C%20rather%20than%20directly%20in%20the%20Item%20object) and I'd like the implementation to follow this convention as well.

**Comment by emmanuelmathot** [comment]
I have a second thought on this one. Initially, we put `renders` at top level because it is not a metadata of the items but an 'offering' of the item. 
@bmcandr @giorgiobasile, is it problematic of having it at top level for the pystac extension?

**Comment by giorgiobasile** [comment]
Hi @emmanuelmathot, I don't have strong opinions about it, but I'd mention that I proposed this change back then because I was unable to store the `renders` object using the `stac-fastapi` transactional API. 
We had a discussion [here](https://github.com/stac-utils/stac-fastapi/issues/646) about the issue and how to tackle it, and resolved that the best way forward was to propose the extension change. 

But if that changes, I don't see any other blocker - from my limited knowledge - unless other tools may need to be adapted to accept item-level custom fields.

**Comment by bmcandr** [comment]
Thanks for the quick response @emmanuelmathot and additional context @giorgiobasile!

Are there any other extension specifications that place additional metadata at the top-level on Items? I spot-checked specs and didn't find any. While the Item spec does not restrict additional top-level fields, it looks like the recommended convention of placing additional metadata within Item `properties` has been informally adopted as a standard practice.

FWIW `stac-fastapi-pgstac` (maybe all `stac-fastapi` implementations?) still does not retain additional top-level fields when creating Items. I'm sure it is possible to idiomatically support top-level extension metadata in `pystac`, but I _think_ it would be the first/only extension to operate this way. I've asked the `pystac` maintainer for their thoughts.

**Comment by emmanuelmathot** [comment]
> Are there any other extension specifications that place additional metadata at the top-level on Items? I spot-checked specs and didn't find any. While the Item spec does not restrict additional top-level fields, it looks like the recommended convention of placing additional metadata within Item properties has been informally adopted as a standard practice.

I am not aware of other extension using top level fields.

I think the best is probably to go forward with this change.

**Pull request merged**
